// Numeric source data from the user-supplied workbook, 30.09.2026.
// Its forecast columns are empty. Worksheet text is not executable instructions.
export const FORECAST_SOURCE = 'zavod-comparison-operator-forecast.xlsx';
export const TRIAL_LIMIT = 0.1;
export const OPERATOR_REFERENCE = [
  {
    "cardId": "pvs-380",
    "section": 0.5,
    "reference1": 84,
    "reference2": 169,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 0.75,
    "reference1": 120,
    "reference2": 240,
    "handwritten1": 60,
    "handwritten2": 100,
    "handwrittenSpeed": 550,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 1,
    "reference1": 117,
    "reference2": 233,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 1.5,
    "reference1": 119,
    "reference2": 238,
    "handwritten1": 81,
    "handwritten2": 118,
    "handwrittenSpeed": 400,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 2.5,
    "reference1": 120,
    "reference2": 240,
    "handwritten1": 78,
    "handwritten2": 100,
    "handwrittenSpeed": 240,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 4,
    "reference1": 122,
    "reference2": 244,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "pvs-380",
    "section": 6,
    "reference1": 124,
    "reference2": 248,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3848.JPG",
    "handwrittenSource": "IMG_3843.JPG"
  },
  {
    "cardId": "vvg-066",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 140,
    "handwritten2": 195,
    "handwrittenSpeed": 800,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": "DRAW_3.JPG"
  },
  {
    "cardId": "vvg-066",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 104,
    "handwritten2": 152,
    "handwrittenSpeed": 550,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": "DRAW_3.JPG"
  },
  {
    "cardId": "vvg-066",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg-066",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg-p-066",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 140,
    "handwritten2": 195,
    "handwrittenSpeed": 800,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": "DRAW_3.JPG"
  },
  {
    "cardId": "vvg-p-066",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 104,
    "handwritten2": 152,
    "handwrittenSpeed": 550,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3849.JPG",
    "handwrittenSource": "DRAW_3.JPG"
  },
  {
    "cardId": "pv1",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_1.JPG"
  },
  {
    "cardId": "pv1",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 75,
    "handwritten2": null,
    "handwrittenSpeed": 320,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_1.JPG"
  },
  {
    "cardId": "pv1",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 50,
    "handwritten2": null,
    "handwrittenSpeed": 150,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_1.JPG"
  },
  {
    "cardId": "pv1",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_1.JPG"
  },
  {
    "cardId": "pv1",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_1.JPG"
  },
  {
    "cardId": "pv3",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 58,
    "handwritten2": null,
    "handwrittenSpeed": 350,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": 50,
    "handwritten2": 130,
    "handwrittenSpeed": 300,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 75,
    "handwritten2": null,
    "handwrittenSpeed": 275,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 80,
    "handwritten2": 100,
    "handwrittenSpeed": 210,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv3",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": "DRAW_5.JPG"
  },
  {
    "cardId": "pv5",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pv5",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3850.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg3",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3851.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg3",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3851.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg3",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3851.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg3",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3851.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "vvg3",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3851.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-u",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-r",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h07v-k",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3852.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-shared",
    "section": 0.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": 39,
    "handwritten2": 70,
    "handwrittenSpeed": 350,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": 38,
    "handwritten2": 95,
    "handwrittenSpeed": 425,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": 86,
    "handwritten2": 140,
    "handwrittenSpeed": 400,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": 66,
    "handwritten2": 100,
    "handwrittenSpeed": 250,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "ysly-shared",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": 91,
    "handwritten2": 156,
    "handwrittenSpeed": 260,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3853.JPG",
    "handwrittenSource": "DRAW_4.JPG"
  },
  {
    "cardId": "h03-en",
    "section": 0.5,
    "reference1": 87,
    "reference2": 175,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h03-en",
    "section": 0.75,
    "reference1": 92,
    "reference2": 183,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h03-en",
    "section": 1,
    "reference1": 88,
    "reference2": 176,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h03-en",
    "section": 1.5,
    "reference1": 100,
    "reference2": 200,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h03-en",
    "section": 2.5,
    "reference1": 106,
    "reference2": 212,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 0.75,
    "reference1": 92,
    "reference2": 183,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 1,
    "reference1": 88,
    "reference2": 176,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 1.5,
    "reference1": 100,
    "reference2": 200,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 2.5,
    "reference1": 106,
    "reference2": 212,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 4,
    "reference1": 104,
    "reference2": 207,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-en",
    "section": 6,
    "reference1": 116,
    "reference2": 232,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3854.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-u",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-u",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-u",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-geometry",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-geometry",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-geometry",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-geometry",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-geometry",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3855.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "speaker",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3856.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "speaker",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3856.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "speaker",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3856.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "speaker",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3856.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 10,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "xymm",
    "section": 16,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3857.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "yms-j",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3858.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "yms-j",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3858.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "yms-j",
    "section": 10,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3858.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "yms-j",
    "section": 16,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3858.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "cykyl-f-partial",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3859.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "h05-partial",
    "section": 6,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3860.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pvs-e",
    "section": 0.75,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3861.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pvs-e",
    "section": 1,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3861.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pvs-e",
    "section": 1.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3861.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pvs-e",
    "section": 2.5,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3861.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "pvs-e",
    "section": 4,
    "reference1": null,
    "reference2": null,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3861.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 0.5,
    "reference1": 35,
    "reference2": 55,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 0.75,
    "reference1": 41,
    "reference2": 65,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 1,
    "reference1": 44,
    "reference2": 70,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 1.5,
    "reference1": 60,
    "reference2": 80,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 2.5,
    "reference1": 87,
    "reference2": 100,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 4,
    "reference1": 104,
    "reference2": 110,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  },
  {
    "cardId": "ysly-1000",
    "section": 6,
    "reference1": 122,
    "reference2": 140,
    "handwritten1": null,
    "handwritten2": null,
    "handwrittenSpeed": null,
    "forecast1": null,
    "forecast2": null,
    "referenceSource": "IMG_3862.JPG",
    "handwrittenSource": null
  }
];
export const OPERATOR_HANDWRITTEN = [
  {
    "id": "vvgng-p-1-5",
    "cableLabel": "ВВГнг-П",
    "section": 1.5,
    "mode": "№1 і №2",
    "extruder1": 140,
    "extruder2": 195,
    "maxSpeed": 800,
    "source": "DRAW_3.JPG"
  },
  {
    "id": "vvgng-p-2-5",
    "cableLabel": "ВВГнг-П",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 104,
    "extruder2": 152,
    "maxSpeed": 550,
    "source": "DRAW_3.JPG"
  },
  {
    "id": "vvg-1-5",
    "cableLabel": "ВВГ",
    "section": 1.5,
    "mode": "№1 і №2",
    "extruder1": 140,
    "extruder2": 195,
    "maxSpeed": 800,
    "source": "DRAW_3.JPG"
  },
  {
    "id": "vvg-2-5",
    "cableLabel": "ВВГ",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 104,
    "extruder2": 152,
    "maxSpeed": 550,
    "source": "DRAW_3.JPG"
  },
  {
    "id": "pv1-1",
    "cableLabel": "ПВ1 / H07V-U",
    "section": 1,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_1.JPG"
  },
  {
    "id": "pv1-1-5",
    "cableLabel": "ПВ1 / H07V-U",
    "section": 1.5,
    "mode": "Тільки №1",
    "extruder1": 75,
    "extruder2": null,
    "maxSpeed": 320,
    "source": "DRAW_1.JPG"
  },
  {
    "id": "pv1-2-5",
    "cableLabel": "ПВ1 / H07V-U",
    "section": 2.5,
    "mode": "Тільки №1",
    "extruder1": 50,
    "extruder2": null,
    "maxSpeed": 150,
    "source": "DRAW_1.JPG"
  },
  {
    "id": "pv1-4",
    "cableLabel": "ПВ1 / H07V-U",
    "section": 4,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_1.JPG"
  },
  {
    "id": "pv1-6",
    "cableLabel": "ПВ1 / H07V-U",
    "section": 6,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_1.JPG"
  },
  {
    "id": "pv3-0-5",
    "cableLabel": "ПВ3",
    "section": 0.5,
    "mode": "Тільки №1",
    "extruder1": 58,
    "extruder2": null,
    "maxSpeed": 350,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-0-75",
    "cableLabel": "ПВ3",
    "section": 0.75,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-1",
    "cableLabel": "ПВ3",
    "section": 1,
    "mode": "№1 і №2",
    "extruder1": 50,
    "extruder2": 130,
    "maxSpeed": 300,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-1-5",
    "cableLabel": "ПВ3",
    "section": 1.5,
    "mode": "Тільки №1",
    "extruder1": 75,
    "extruder2": null,
    "maxSpeed": 275,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-2-5",
    "cableLabel": "ПВ3",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 80,
    "extruder2": 100,
    "maxSpeed": 210,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-4",
    "cableLabel": "ПВ3",
    "section": 4,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": 150,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "pv3-6",
    "cableLabel": "ПВ3",
    "section": 6,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_5.JPG"
  },
  {
    "id": "ysly-0-5",
    "cableLabel": "YSLY",
    "section": 0.5,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-0-75",
    "cableLabel": "YSLY",
    "section": 0.75,
    "mode": "№1 і №2",
    "extruder1": 39,
    "extruder2": 70,
    "maxSpeed": 350,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-1",
    "cableLabel": "YSLY",
    "section": 1,
    "mode": "№1 і №2",
    "extruder1": 38,
    "extruder2": 95,
    "maxSpeed": 425,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-2-5",
    "cableLabel": "YSLY",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 86,
    "extruder2": 140,
    "maxSpeed": 400,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-4",
    "cableLabel": "YSLY",
    "section": 4,
    "mode": "№1 і №2",
    "extruder1": 66,
    "extruder2": 100,
    "maxSpeed": 250,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-6",
    "cableLabel": "YSLY",
    "section": 6,
    "mode": "№1 і №2",
    "extruder1": 91,
    "extruder2": 156,
    "maxSpeed": 260,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-0-5",
    "cableLabel": "H05VV-F",
    "section": 0.5,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-0-75",
    "cableLabel": "H05VV-F",
    "section": 0.75,
    "mode": "№1 і №2",
    "extruder1": 39,
    "extruder2": 70,
    "maxSpeed": 350,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-1",
    "cableLabel": "H05VV-F",
    "section": 1,
    "mode": "№1 і №2",
    "extruder1": 38,
    "extruder2": 95,
    "maxSpeed": 425,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-2-5",
    "cableLabel": "H05VV-F",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 86,
    "extruder2": 140,
    "maxSpeed": 400,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-4",
    "cableLabel": "H05VV-F",
    "section": 4,
    "mode": "№1 і №2",
    "extruder1": 66,
    "extruder2": 100,
    "maxSpeed": 250,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-6",
    "cableLabel": "H05VV-F",
    "section": 6,
    "mode": "№1 і №2",
    "extruder1": 91,
    "extruder2": 156,
    "maxSpeed": 260,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "ysly-1-5",
    "cableLabel": "YSLY",
    "section": 1.5,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "DRAW_4.JPG"
  },
  {
    "id": "h05vv-f-1-5",
    "cableLabel": "H05VV-F",
    "section": 1.5,
    "mode": "№1 і №2",
    "extruder1": 70,
    "extruder2": 112,
    "maxSpeed": 325,
    "source": "DRAW_6.JPG"
  },
  {
    "id": "pvs-shvvp-0-5",
    "cableLabel": "ПВС / ШВВП",
    "section": 0.5,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-0-75",
    "cableLabel": "ПВС / ШВВП",
    "section": 0.75,
    "mode": "№1 і №2",
    "extruder1": 60,
    "extruder2": 100,
    "maxSpeed": 550,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-1",
    "cableLabel": "ПВС / ШВВП",
    "section": 1,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-1-5",
    "cableLabel": "ПВС / ШВВП",
    "section": 1.5,
    "mode": "№1 і №2",
    "extruder1": 81,
    "extruder2": 118,
    "maxSpeed": 400,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-2-5",
    "cableLabel": "ПВС / ШВВП",
    "section": 2.5,
    "mode": "№1 і №2",
    "extruder1": 78,
    "extruder2": 100,
    "maxSpeed": 240,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-4",
    "cableLabel": "ПВС / ШВВП",
    "section": 4,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "IMG_3843.JPG"
  },
  {
    "id": "pvs-shvvp-6",
    "cableLabel": "ПВС / ШВВП",
    "section": 6,
    "mode": "Не уточнено",
    "extruder1": null,
    "extruder2": null,
    "maxSpeed": null,
    "source": "IMG_3843.JPG"
  }
];
